description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'ric-docker.jfrog.io/ricardo-ch/compliance:<<parameters.tag>>'
    auth:
      username: << parameters.username >>
      password: << parameters.password >>
parameters:
  tag:
    default: test
    description: >
      Pick a specific circleci/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
  username:
    type: string
    description: >
      Artifactory username.
  password:
    type: string
    description: >
      Artifactory password.
